services:
  db:
    image: postgres
    ports:
      - 6431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: horde_pro
      POSTGRES_PORT: 6431
