services:
  db:
    image: postgres
    ports:
      - 6431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: horde
      POSTGRES_PORT: 6431
    command: postgres -c shared_buffers=256MB -c max_connections=200

