on: push

env:
  ELIXIR_ERL_OPTIONS: -kernel prevent_overlapping_partitions false

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_URL: "ecto://postgres:postgres@localhost:5431/horde_pro"
      MIX_ENV: "test"

    strategy:
      fail-fast: false
      matrix:
        elixir-version: [1.17, 1.16, 1.15, 1.14]
        otp-version: [27, 26, 25, 24]
        exclude:
          - elixir-version: 1.13
            otp-version: 26
          - elixir-version: 1.14
            otp-version: 27
          - elixir-version: 1.15
            otp-version: 27

    services:
      postgres:
        image: postgres:17.0
        ports:
          - 5431:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: horde_pro
          POSTGRES_PORT: 5431

    name: Tests
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir-version }}
          otp-version: ${{ matrix.otp-version }}

      - run: mix deps.get

      - run: mix compile --warnings-as-errors
        if: matrix.elixir-version == 1.17 && matrix.otp-version == 27

      - run: mix format --check-formatted
        if: matrix.elixir-version == 1.17 && matrix.otp-version == 27

      - run: mix do ecto.create --quiet -r HordeProTest.Repo, ecto.migrate -r HordeProTest.Repo, test
